/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package rlez */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void RlezInit(void);
extern void RlezEnd(void);
extern GoInt32 RlezGetReturnSize(void);
extern GoInt32 RlezGetReturnTypeNameSize(void);
extern void RlezGetReturnType(GoUintptr p);
extern void RlezGetReturnData(GoUintptr p);
extern void RlezGroup(GoInt32 id, GoUintptr name);
extern void RlezDelete(GoInt32 id);
extern void RlezDeleteGroup(GoUintptr name);
extern void RlezDeleteAll(void);
extern void RlezLoadTempDir(GoUintptr return_pointer);
extern void RlezDeleteDir(GoUintptr path);
extern void RlezOpenWindow(GoInt32 width, GoInt32 height);
extern void RlezSetWindowFocus(void);
extern GoInt32 RlezCheckWindowFocus(void);
extern void RlezSetWindowSize(GoInt32 width, GoInt32 height);
extern void RlezSetWindowPosition(GoInt32 x, GoInt32 y);
extern GoInt32 RlezGetWindowX(void);
extern GoInt32 RlezGetWindowY(void);
extern GoUintptr RlezGetWindowHandle(void);
extern void RlezSetWindowIcon(GoInt32 texture);
extern GoInt32 RlezGetWindowWidth(void);
extern GoInt32 RlezGetWindowHeight(void);
extern GoInt32 RlezGetWidth(GoInt32 resource);
extern GoInt32 RlezGetHeight(GoInt32 resource);
extern GoInt32 RlezCheckWindowState(GoUintptr flag);
extern void RlezSetWindowState(GoUintptr flag, GoInt32 value);
extern void RlezSetWindowTitle(GoUintptr title);
extern GoInt32 RlezCheckWindowClose(void);
extern GoInt32 RlezGetFrameRate(void);
extern void RlezSetFrameRate(GoInt32 fps);
extern GoInt32 RlezGetDisplayCount(void);
extern GoInt32 RlezGetCurrentDisplay(void);
extern GoInt32 RlezGetDisplayX(GoInt32 display);
extern GoInt32 RlezGetDisplayY(GoInt32 display);
extern GoInt32 RlezGetDisplayWidth(GoInt32 display);
extern GoInt32 RlezGetDisplayHeight(GoInt32 display);
extern void RlezGetBackend(GoUintptr return_pointer);
extern GoFloat64 RlezGetTime(void);
extern void RlezBeginDraw(GoInt32 resource);
extern void RlezBeginWindow(void);
extern void RlezEndDraw(void);
extern void RlezBegin2D(GoFloat64 offset_x, GoFloat64 offset_y, GoFloat64 target_x, GoFloat64 target_y, GoFloat64 rotation, GoFloat64 zoom);
extern void RlezEnd2D(void);
extern void RlezBegin3D(GoFloat64 position_x, GoFloat64 position_y, GoFloat64 position_z, GoFloat64 target_x, GoFloat64 target_y, GoFloat64 target_z, GoFloat64 up_x, GoFloat64 up_y, GoFloat64 up_z, GoFloat64 fovy, GoInt32 projection);
extern void RlezEnd3D(void);
extern void RlezBeginBlend(GoUintptr mode);
extern void RlezBeginBlendCustom(GoUintptr src_factor, GoUintptr dest_factor, GoUintptr equation);
extern void RlezBeginBlendCustomSeparate(GoUintptr src_rgb, GoUintptr dest_rgb, GoUintptr src_alpha, GoUintptr dest_alpha, GoUintptr eq_rgb, GoUintptr eq_alpha);
extern void RlezEndBlend(void);
extern void RlezBeginShader(GoInt32 resource);
extern void RlezEndShader(void);
extern void RlezPerspective(GoFloat64 fovy, GoFloat64 aspect, GoFloat64 near, GoFloat64 far);
extern void RlezFrustum(GoFloat64 left, GoFloat64 right, GoFloat64 bottom, GoFloat64 top, GoFloat64 near, GoFloat64 far);
extern void RlezOrtho(GoFloat64 left, GoFloat64 right, GoFloat64 bottom, GoFloat64 top, GoFloat64 near, GoFloat64 far);
extern void RlezPushMatrix(void);
extern void RlezPopMatrix(void);
extern void RlezTranslate(GoFloat64 x, GoFloat64 y, GoFloat64 z);
extern void RlezScale(GoFloat64 x, GoFloat64 y, GoFloat64 z);
extern void RlezRotateAxis(GoFloat64 angle, GoFloat64 x, GoFloat64 y, GoFloat64 z);
extern void RlezRotateX(GoFloat64 angle);
extern void RlezRotateY(GoFloat64 angle);
extern void RlezRotateZ(GoFloat64 angle);
extern void RlezRotate(GoFloat64 angle);
extern void RlezLocalToWorld(GoFloat64 sx, GoFloat64 sy, GoFloat64 sz, GoUintptr dx, GoUintptr dy, GoUintptr dz);
extern void RlezWorldToLocal(GoFloat64 sx, GoFloat64 sy, GoFloat64 sz, GoUintptr dx, GoUintptr dy, GoUintptr dz);
extern void RlezWorldToScreen(GoFloat64 screen_x, GoFloat64 screen_y, GoFloat64 screen_w, GoFloat64 screen_h, GoFloat64 sx, GoFloat64 sy, GoFloat64 sz, GoUintptr dx, GoUintptr dy, GoUintptr dz, GoUintptr dw);
extern GoInt32 RlezLoadRenderTexture(GoInt32 width, GoInt32 height);
extern GoInt32 RlezLoadTexture(GoUintptr path);
extern GoInt32 RlezLoadTextureFromMemory(GoUintptr file_type, GoUintptr data, GoInt32 size);
extern void RlezSetTextureFilter(GoInt32 texture, GoUintptr filter_type);
extern void RlezSetTextureMipmaps(GoInt32 texture);
extern GoInt32 RlezLoadFont(GoUintptr path, GoInt32 font_size, GoUintptr target_string, GoInt32 target_image_width, GoInt32 target_image_height);
extern GoInt32 RlezLoadFontFromMemory(GoUintptr font_data, GoInt32 font_data_size, GoInt32 font_size, GoUintptr target_string, GoInt32 target_image_width, GoInt32 target_image_height);
extern void RlezLoadPixels(GoInt32 texture, GoUintptr format);
extern void RlezCopyPixels(GoInt32 src_offset, GoInt32 src_length, GoUintptr dest_pointer, GoInt32 dest_offset);
extern void RlezRestorePixels(GoUintptr src_pointer, GoInt32 src_offset, GoInt32 src_length, GoInt32 dest_offset);
extern void RlezGetPixel(GoInt32 x, GoInt32 y);
extern void RlezSetPixel(GoInt32 x, GoInt32 y);
extern void RlezUpdatePixels(void);
extern void RlezSavePixels(GoUintptr path);
extern void RlezUnloadPixels(void);
extern void RlezBackground(GoInt32 r, GoInt32 g, GoInt32 b, GoInt32 a);
extern void RlezBeginShape(GoUintptr mode, GoInt32 auto_normal, GoInt32 resource);
extern void RlezVertex(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 u, GoFloat64 v, GoInt32 r, GoInt32 g, GoInt32 b, GoInt32 a, GoFloat64 nx, GoFloat64 ny, GoFloat64 nz);
extern void RlezEndShape(void);
extern GoInt32 RlezEndMesh(void);
extern void RlezSetMeshTexture(GoInt32 mesh, GoInt32 texture);
extern GoInt32 RlezLoadModel(GoUintptr path, GoInt32 load_animation);
extern void RlezFromMeshToModel(GoInt32 mesh);
extern void RlezSetModelTexture(GoInt32 model, GoInt32 material_index, GoUintptr map_name, GoInt32 texture);
extern GoInt32 RlezGetAnimationCount(GoInt32 model);
extern GoInt32 RlezGetAnimationId(GoInt32 model, GoUintptr name);
extern GoInt32 RlezGetAnimationFrames(GoInt32 model, GoInt32 id);
extern void RlezSetModelAnimation(GoInt32 model, GoInt32 id, GoFloat64 frame);
extern void RlezSetModelAnimationBlend(GoInt32 model, GoInt32 a_id, GoFloat64 a_frame, GoInt32 b_id, GoFloat64 b_frame, GoFloat64 blend);
extern void RlezColor(GoInt32 r, GoInt32 g, GoInt32 b, GoInt32 a);
extern GoInt32 RlezGetColorR(void);
extern GoInt32 RlezGetColorG(void);
extern GoInt32 RlezGetColorB(void);
extern GoInt32 RlezGetColorA(void);
extern void RlezDrawMesh(GoInt32 mesh);
extern void RlezDrawModel(GoInt32 model);
extern void RlezDrawText(GoInt32 font, GoUintptr text, GoFloat64 x, GoFloat64 y, GoFloat64 size, GoFloat64 spacing);
extern void RlezDrawLine(GoFloat64 x1, GoFloat64 y1, GoFloat64 z1, GoFloat64 x2, GoFloat64 y2, GoFloat64 z2);
extern void RlezDrawRect(GoFloat64 x, GoFloat64 y, GoFloat64 width, GoFloat64 height, GoInt32 fill);
extern void RlezDrawEllipse(GoFloat64 x, GoFloat64 y, GoFloat64 width, GoFloat64 height, GoInt32 fill);
extern void RlezDrawBox(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 width, GoFloat64 height, GoFloat64 depth, GoInt32 fill);
extern void RlezDrawSphere(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 size, GoInt32 rings, GoInt32 slices, GoInt32 fill);
extern void RlezDrawCylinder(GoFloat64 x1, GoFloat64 y1, GoFloat64 z1, GoFloat64 x2, GoFloat64 y2, GoFloat64 z2, GoFloat64 size1, GoFloat64 size2, GoInt32 sides, GoInt32 fill);
extern void RlezDrawCapsule(GoFloat64 x1, GoFloat64 y1, GoFloat64 z1, GoFloat64 x2, GoFloat64 y2, GoFloat64 z2, GoFloat64 size, GoInt32 slices, GoInt32 rings, GoInt32 fill);
extern void RlezDrawTexture(GoInt32 texture, GoInt32 src_x, GoInt32 src_y, GoInt32 src_w, GoInt32 src_h, GoFloat64 dest_x, GoFloat64 dest_y, GoFloat64 dest_w, GoFloat64 dest_h);
extern GoInt32 RlezLoadShaderFromMemory(GoUintptr vertex_code, GoUintptr fragment_code);
extern GoInt32 RlezLoadShader(GoUintptr vertex_code_path, GoUintptr fragment_code_path);
extern GoInt32 RlezLoadSoundFromMemory(GoUintptr file_type, GoUintptr sound_data, GoInt32 sound_data_size, GoInt32 is_music, GoFloat64 music_update_time, GoInt32 music_update_samples);
extern GoInt32 RlezLoadSound(GoUintptr path, GoInt32 is_music, GoFloat64 music_update_time, GoInt32 music_update_samples);
extern void RlezStopSound(GoInt32 sound);
extern void RlezPauseSound(GoInt32 sound);
extern void RlezResumeSound(GoInt32 sound);
extern void RlezPlaySound(GoInt32 sound, GoInt32 music_loop);
extern GoInt32 RlezGetSoundStatus(GoInt32 sound);
extern GoFloat64 RlezGetSoundTime(GoInt32 sound);
extern void RlezSetSoundTime(GoInt32 sound, GoFloat64 set_time);
extern GoFloat64 RlezGetSoundLength(GoInt32 sound);
extern void RlezSetSoundPitch(GoInt32 sound, GoFloat64 pitch);
extern void RlezSetSoundVolume(GoInt32 sound, GoFloat64 volume);
extern void RlezSetSoundPan(GoInt32 sound, GoFloat64 pan);
extern GoInt32 RlezGetKey(GoUintptr name);
extern GoInt32 RlezGetMouseButton(GoUintptr name);
extern GoInt32 RlezGetMouseX(void);
extern GoInt32 RlezGetMouseY(void);
extern void RlezSetMousePosition(GoInt32 x, GoInt32 y);
extern void RlezSetMouseVisible(GoInt32 visible);
extern GoInt32 RlezCheckMouseInWindow(void);
extern GoFloat64 RlezGetMouseWheelX(void);
extern GoFloat64 RlezGetMouseWheelY(void);
extern GoInt32 RlezCheckGamepad(GoInt32 gamepad);
extern GoInt32 RlezGetGamepadButton(GoInt32 gamepad, GoUintptr button);
extern GoInt32 RlezGetAxisCount(GoInt32 gamepad);
extern GoFloat64 RlezGetGamepadAxis(GoInt32 gamepad, GoInt32 axis);
extern void RlezSetGamepadVibration(GoInt32 gamepad, GoFloat64 left, GoFloat64 right, GoFloat64 duration);

#ifdef __cplusplus
}
#endif
